# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
- type: subscribe
  options:
    url: https://proxypoolss.tk/sip002/sub
- type: subscribe
  options:
    url: https://proxypoolss.tk/vmess/sub
- type: subscribe
  options:
    url: https://proxypoolss.tk/trojan/sub
- type: subscribe
  options:
    url: https://proxypoolss.tk
- type: subscribe
  options:
    url: https://proxypool.ga
- type: subscribe
  options:
    url: https://pool-840979.asia1.kinto.io
- type: subscribe
  options:
    url: https://free-ss.site/
- type: subscribe
  options:
    url: https://bihai.cf/
- type: subscribe
  options:
    url: https://github.com/freefq
- type: subscribe
  options:
    url: https://m.ssrtool.us/
- type: subscribe
  options:
    url: https://tro.zqwnan.tk/
- type: subscribe
  options:
    url: https://ss.dswang.ga/
- type: subscribe
  options:
    url: https://sspool.herokuapp.com/
- type: subscribe
  options:    
    url: https://proxy.moneyfly.club/
- type: subscribe
  options:
    url: http://www.6166888.xyz/
- type: subscribe
  options:    
    url: https://proxypoolsstest.herokuapp.com/
- type: subscribe
  options:
    url: http://proxypool.turinglabs.net/
- type: subscribe
  options:
    url: https://v2cross.com/
- type: subscribe
  options:
    url: https://www.vpngate.net/cn/
- type: subscribe
  options:
    url: https://freevpn.gg/
- type: subscribe
  options:
    url: https://m.freeopenvpn.org/en/
- type: subscribe
  options:
    url: https://www.vpnbook.com/
- type: subscribe
  options:
    url: https://www.racevpn.com/
- type: subscribe
  options:
    url: Lncn.org
- type: subscribe
  options:
    url: https://lightyearvpn.com/zh/free-vpn
- type: subscribe
  options:
    url: https://view.freev2ray.org/
- type: subscribe
  options:
    url: https://free.kingfu.cf/sip002/sub
- type: subscribe
  options:
    url: https://free.kingfu.cf/vmess/sub
- type: subscribe
  options:
    url: https://free.kingfu.cf/trojan/sub
   
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

- type: tgchannel
  options:
    channel: v2rayshare
    num: 200

- type: tgchannel
  options:
    channel: TJiaSu_Bot
    num: 200

- type: tgchannel
  options:
    channel: v2List
    num: 200    
    
- type: tgchannel
  options:
    channel: ssList
    num: 200
    
- type: tgchannel
  options:
    channel: ssrList
    num: 200    

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml

# 某个网站抓取
- type: web-freessrxyz
  options:
